### ISSUE TITLE
live.dallasmakerspace.org & dm.dallasmakerspace.org

### ISSUE THREAD

**Issue by coul** [Dallas-Makerspace/tracker#13]
please set up subdomains live.dallasmakerspace.org & dm.dallasmakerspace.org

Thank you.

**Comment by denzuko** [comment]
Where are we pointing them to? ie IP address or Apex name address

**Comment by coul** [comment]
actually, we can try multi-site as discussed

**Comment by coul** [comment]
If you are having issues setting up multi-site, let me know and I can show you next time I'm at the space. I've done it multiple times and it's pretty easy

**Comment by denzuko** [comment]
>  multi-site as discuss

If we're referring to [enabling wordpress mu](https://premium.wpmudev.org/blog/ultimate-guide-multisite/) on to the production wordpress code base then we'll need to triage this request first then get the work scheduled on the calendar and the procedures documented.

**Comment by coul** [comment]
Do you have an eta on this?

**Comment by coul** [comment]
Also, please let me know if there's anything I can do to help move this along

**Comment by denzuko** [comment]
@coul I've built out the staging environment for testing the wpmu and other services. As a committee chair you already have a login on the community grid on motherboard.dms.local via your AD credentials.

I have a video showing how to deploy wordpress to the new staging environment that might just help:
  https://drive.google.com/file/d/1VbTE1sWQaQbCNb3y4jwE3DRKBU-qzAY-/view

Luke and I do have a hack-a-thon scheduled next week to get the CICD system out of beta testing and push the new production environment into AWS with the first major service being deployed is the DMS wordpress with WPMU enabled.
