### ISSUE TITLE
admin group credentials still not working

### ISSUE THREAD

**Issue by coul** [Dallas-Makerspace/tracker#15]
## Expected Behavior 

When a member installing software gets admin privilege required, I enter my creds > works

## Actual Behavior

When a member installing software gets admin privilege required, I enter my creds > not working

## Steps to Reproduce the Problem

  1. verified control panel user credentials
  2. spoke with @denzuko who requested ticket 
  3. opened issue 3 days ago but was closed prior to completion https://github.com/Dallas-Makerspace/tracker/issues/14
  4. spoke with Dwight again the day the issue was closed
  5. posting redefined issue now

## Specifications
(The version of the project, operating system, hardware etc.)

Effecting all DMS workstations

**Comment by coul** [comment]
If you are having issues with this let me know next time I'm at the space and I can help you. I would do it myself, but obviously, I don't have access...

**Comment by denzuko** [comment]
Putting this on @StanSimmons radar as this sounds like a bigger issue to address than simple missing group permissions in AD for one account.

**Comment by denzuko** [comment]
> When a member installing software

Also, what software are these members installing?
