### ISSUE TITLE
LDAP Open to public internet

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/tracker#17]
## Expected Behavior 
Active Directory servers secured

## Actual Behavior
Shodan crawled physical.dallasmakerspace.org and documented  636 as open along with publishing internal ip space from prdc1's certificate

## Steps to Reproduce the Problem

  1. visit https://www.shodan.io/host/47.190.37.3#636
  1. `nmap -p 636 physical.dallasmakerspace.org` on any machine external of dms.local

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by denzuko** [comment]
Paging @StanSimmons 

Is this a service we actually need open? PRDC1 is accessible via the vpn and anything public (ie otka) is already going to prdc2/prdc3

**Comment by denzuko** [comment]
Open for comments on ticket https://github.com/Dallas-Makerspace/tracker/issues/39

**Comment by PeterS242** [comment]
The port is definitely open.  That really doesn't sound like something that
needs to be open to the net.  Are there any logs that show malicious
crawling yet?

[root@linux ~]# openssl s_client -connect physical.dallasmakerspace.org:636
CONNECTED(00000003)
depth=1 DC = local, DC = dms, CN = dms-PRDC2-CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=PRDC1.dms.local
   i:/DC=local/DC=dms/CN=dms-PRDC2-CA
 1 s:/DC=local/DC=dms/CN=dms-PRDC2-CA
   i:/DC=local/DC=dms/CN=dms-PRDC1-CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFzzCCBLegAwIBAgITbQAAAAOeZSEXPyYQpwAAAAAAAzANBgkqhkiG9w0BAQUF
<SNIP>
S34B6IlDBPlcrxxpDNIMoD2qil9ZeRnFI51MhdAE4Pq0JsiB3+9Fq7sYHjBH5qaI
unPj
-----END CERTIFICATE-----
subject=/CN=PRDC1.dms.local
issuer=/DC=local/DC=dms/CN=dms-PRDC2-CA
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 3395 bytes and written 441 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID:
6C070000502FA3AC6BF3DCBA86ECA5160222028F87F22970DA1E998AE6A34AA6
    Session-ID-ctx:
    Master-Key:
57B2BFBBFCFB6CC181DE7C0AD6F33E1B0B4087289CC2ED908F3AF9A084CDA3E6DC5276BB7E76310D45EA66D282041F42
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1527088132
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---

**Comment by denzuko** [comment]
The previous implementer did not  seam to understand firewalls and chose to use a cloud based saml/oauth solution which at the time required the port to be open.

We have since then improved the firewall, vlans, and vpn setup. 

I'm not commenting either pro nor con of supporting a public accessible ldap just more to the current state of things and other potential changes.

About the only reason why I would see any reason for the ldap to be available is that we're a non-profit org that maintains a directory of members. The other side of that is there's a request for a member based "facebook"/alumni tool with features that we had in the helpline board. We'll most likely be tieing that in with talk and discord anyways which both use a restful api and [discourse's api](https://meta.discourse.org/t/how-do-i-get-a-list-of-all-users-from-the-api/24261) provides less details but is able to provide a member directory feature.

**Comment by denzuko** [comment]
There's also procedures that can be implemented for limiting what is viewable based on groups, thus increasing layers of separation and ensuring only what's needed per service account is available.

http://www.itprotoday.com/management-mobility/hiding-active-directory-objects-and-attributes

We may want to do this one despite what direction one takes to protect not just PII data but also badge ids.

This would also require an audit of all things that touch the active directory for any reason.

**Comment by PeterS242** [comment]
I think that probably the ideal solution would be to have a static OpenLDAP
service that responds to external requests and has a trimmed-down
minimalized copy of the internal version.  It would also be sync'ed
regularly.  That would be best, but of course would require man hours to
implement and test..

Peter

**Comment by denzuko** [comment]
LDAP port disabled on the public interface, still access able via openvpn and the l2tp vpn.
