### ISSUE TITLE
Opencast lecture computer does not have DNS entry

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/tracker#31]
## Expected Behavior 

To be able to do a DNS lookup for "ocast-lecture" and get ip address 192.168.200.51 and perhaps the reverse

## Actual Behavior

No such address found

## Steps to Reproduce the Problem

  1. Login to a linux computer at space
  2. type "host ocast-lecture" 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by denzuko** [comment]
```
Address:  192.168.0.33

> ocast-lecture
Server:  prdc1.dms.local
Address:  192.168.0.33

Name:    ocast-lecture.dms.local
Address:  192.168.200.51

```

@MikeColeGuru  I'm sure that there was someone else that updated this. Could you please have them comment on this ticket so we can document the work.
