### ISSUE TITLE
(bug) PRLXOCAST02 has wrong subnet address

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/tracker#32]
## Expected Behavior 

To be assigned an IP address on the internal server network 192.168.0.0/24

## Actual Behavior

The current DNS address for PRLXOCAST02 is set to 192.168.202.60

**Comment by MikeColeGuru** [comment]
PRLXOCAST02 now has two addresses.

192.168.0.214/24 from DHCP and the default gateway with no VLAN tagging
192.168.202.60/21 on VLAN 2

However I am not getting any traffic on the second address.  Perhaps, the port doesn't accept VLAN Tagging

**Comment by MikeColeGuru** [comment]
It appears the worker and the administrative interface and filestore will be on PRLXOCAST02.  It might benefit from having access to both subnets.

**Comment by denzuko** [comment]
```
> prlxocast02.dms.local
Server:  prdc1.dms.local
Address:  192.168.0.33

Name:    prlxocast02.dms.local
Address:  192.168.200.82

> exit
PS C:\Users\Denzuko.DMS.007> ping prlxocast02

Pinging prlxocast02.dms.local [192.168.200.82] with 32 bytes of data:
Reply from 192.168.200.82: bytes=32 time=1ms TTL=64
Reply from 192.168.200.82: bytes=32 time<1ms TTL=64
Reply from 192.168.200.82: bytes=32 time<1ms TTL=64

Ping statistics for 192.168.200.82:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms
```

I think we where able to get this resolved last night. Can we  confirm that we have resolved this issue?

**Comment by MikeColeGuru** [comment]
It is on the correct subnet and seems to be working well.  However, there is a strange problem that keeps popping up on non-domain computers.   For example, one of the linux boxes in the common room.   When I try to SSH to PRLXOCAST02 it first tells me that the name does not exist .. then I keep trying the ssh command and it eventually finds the name and connects.  Is this a nameserver fail over problem?

I will try this on other non-domain computers and see if it is just that machine.

**Comment by denzuko** [comment]
yes, that does sound like the dns server is not forwarding to the correct authoritative ns server. So one has to keep querying for the domain until there's a roll over to the other ns server. We'll look into that on a seperate ticket.
