### ISSUE TITLE
A Development/Beta Testing website for Calendar

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/tracker#33]
## Expected Behavior 

To be able to demonstrate functionality to those that do not code for testing and debugging.

## Actual Behavior

No such ability exists yet.

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

Something similar to the production website that I have access to, so I can upload and install the calendar.  However you can make it work, is fine with me as long as people can get to it remotely.

**Comment by denzuko** [comment]
preprod deployment via apps.dallasmakerspace.org should work.

need to make sure unit tests pass so docker hub can build the image.
