### ISSUE TITLE
[Maintenance] DMS Talk server maintence window

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/tracker#43]
[Calendar Event](https://calendar.dallasmakerspace.org/events/view/6257)

## Procedure

- Create snapshot
- Take down Talk's vm and attach storage to recovery vm
- Rekey instance and validate sshd_config
- Reattach Storage and Restart VM
- Prune docker
- Setup secondary drive for /docker and expand to 200Gb
- Expand files system for primary drive to match 150Gb block storage size
- Create regular backups of environment + changes sent to AWS ECR as data images
- Setup Rolling Backups with 60/30 warm/cold storage strategy
- Audit automation of updates / upgrades for points of optimization
- Remove snapshot in 3 days

## Backout procedure

- Restore from snapshot

**Comment by clone1018** [comment]
Is this still happening?
