### ISSUE TITLE
Digital Media Admins

### ISSUE THREAD

**Issue by apparently-weird** [Dallas-Makerspace/tracker#44]
## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by denzuko** [comment]
Using mmc I removed all the users (save for system related accounts) from the admin group on each of DM-00x and added the group `Digital Media Local Admins`. Any user in that ad group will be able to act as a local admin within only digital media computers. Whomever that is listed as Digital Media Committee Chair in active directory has permissions to update the `Digital Media Local Admins` group via Active Directory without having to ask infrastructure for changes.
