### ISSUE TITLE
Rebuild PRDC1

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/tracker#48]
## Expected Behavior 

PRDC1 is up and functional on PRVIR02

## Actual Behavior

It isn't installed yet

## Specifications
(The version of the project, operating system, hardware etc.)

We need to rebuild PRDC1 on PRVIR02.

We also need to remove the Virtual IPs on the main router that is currently redirecting PRDC1 to PRDC2 once we have PRDC1 up and on the correct IP address.

**Comment by ghost** [comment]
New Server Build by Draco.  Joined to the domain ad will be promoted after a discussion with Draco and Stan.
Server renamed to PRDC1A.  This will keep the PRDC1a and PRDC1b as the twoDC located and the space and PRDC3 & 4 will remain on AWS.
Attempting to recover the NPS system from the old PRDC1 and implement after Draco, Stan, and I discuss what we end up with.
Unless absolutely necessary I think that abandoning the recovery of CA role on the old PRDC1 would be a good idea.  If we reserect it we will have to undo all the work Draco has put into the CA on PRDC1b.

**Comment by denzuko** [comment]
@woody39205 agreed. The CA stuff was moved to the PFSense and the root CA is publically available on our wiki.

Great job guys. We may have to investigate the impact of the change and maybe setup some RR records in the dns to help mitigate some issues that may show up from the new dns names. But overall this seems to be resolved.
