### ISSUE TITLE
Autodesk Inventor License expired 

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/tracker#57]
## Expected Behavior 
Autodesk Inventor to operate without issue

## Actual Behavior
Prompt to an updated input licence serial

## Steps to Reproduce the Problem

  1. RDP into physical.dallasmakerspace.org
  1.  visit Start > Autodesk Inventor 2016
  1.  Launch Autodesk Inventor 2016

## Specifications
PRWJUMP.dms.local

**Comment by ghost** [comment]
I will be at the space tonight and will see what I can do to help on this.

**Comment by denzuko** [comment]
Thanks woody. If we can deploy it via nuget, gpo, or a powershell script in \\files\infrastructure for repeatability then that would be amazing

**Comment by ghost** [comment]
Yep.  Just need to see what we need to do first then choose the method.

**Comment by denzuko** [comment]
![Imgur](https://i.imgur.com/s8rlkDc.png)

**Comment by denzuko** [comment]
admin-wiki://admin/wiki/Accounts#Autodesk

**Comment by denzuko** [comment]
Pending licence agreement
