### ISSUE TITLE
need access to dms website and blog for updates

### ISSUE THREAD

**Issue by sail-do** [Dallas-Makerspace/tracker#67]
## Expected Behavior 
allow me to edit the content of the website & associated blog
allow me to view the website source

## Actual Behavior
access restricted

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)
As the new PR chair, I wish to update the content.  I also want to review the website design for possible changes.
Cheers, john a. gorman
talkers@dallasmakerspace.org

**Comment by denzuko** [comment]
You have been promoted to administrator. Feel free to login with at anytime.

If you need any further help reply to this ticket or visit chat.dallasmakerspace.org and post in the #infrastructure channel.
