### ISSUE TITLE
Install Docker for Digital Asset Management

### ISSUE THREAD

**Issue by thespacemaker** [Dallas-Makerspace/tracker#69]
## Expected Behavior 
Here's the link for the docker... thanks!

https://hub.docker.com/r/netresearch/phraseanet/

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by denzuko** [comment]
Load balancer maintenance has been completed. Community Grid access should be restored.

In prep, we have also created the following domain in our GTM for your application:
  - digitalmedia.dms.local
  - digitalmedia.dallasmakerspace.org

There is also a repository available for your usage:

   https://github.com/Dallas-Makerspace/digitalmedia.dallasmakerspace.org

Along with the following help desk tag:

https://github.com/Dallas-Makerspace/tracker/labels/System%2FDigital%20Media%20Library

One would still need to spin up an elastic search cluster, mysql cluster, and build an updated version of phraseanet image then deploy to the grid

**Comment by denzuko** [comment]
Application is deployed: https://communitygrid.dms.local/#/stacks/digitalmedia-dms-local?id=1&type=1&external=false

**Comment by denzuko** [comment]
Docker Image: https://hub.docker.com/r/dallasmakerspace/phraseanet/

**Comment by denzuko** [comment]
If Oauth2 authentication or a ldap service account is needed to be created the please submit a change request ticket for those.
