### ISSUE TITLE
Add Adnan (that's me) to the gmail

### ISSUE THREAD

**Issue by thespacemaker** [Dallas-Makerspace/tracker#70]
## Expected Behavior 
I would like to access my gmail but when I do I get this error

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/31951968/45582658-56b42400-b879-11e8-9471-5d6ff270c977.png">

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by denzuko** [comment]
@thespacemaker I've added the needed group to your active directory account. Double check and let us know if there's any further issues.
