### ISSUE TITLE
(Bug) Community Grid Worker nodes out of diskspace

### ISSUE THREAD

**Issue by dms-infrastructure** [Dallas-Makerspace/tracker#78]
## Expected Behavior 
Operational workers

## Actual Behavior
Workers go offline after a time

## Steps to Reproduce the Problem

  1. boot with boot2docker
  1. deploy services

## Delta

  - Rebuild 6 VM with ubuntu and use cicd.dms.local + docker-machine to provision.

**Comment by dms-infrastructure** [comment]
- [x] Should be on the domain
- [x] Should use an adm_* account
- [x] Should use allocated dns names

**Comment by denzuko** [comment]
Compute-02,04,06 are online

**Comment by denzuko** [comment]
both vm hosts need to have Live Migration enabled.

**Comment by denzuko** [comment]
all nodes are back online and joined into a single swarm.
